/* Contains facts for the KEMI knowledge base

Contents:
- multiplicative prefixes
- element names (IUPAC)
- element ENs
- element #protons
- alternate element names
- parent names of mononuclear hydrides
*/
:- module(facts,[
        synonymous/2,
        num_protons/2,
        en/2,
        element_name/2,
        multiplicative_prefix/2,
        parent_hydride_name/2
    ]).


% multiplicative prefixes
multiplicative_prefix(1, "mono").
multiplicative_prefix(2, "di").
multiplicative_prefix(3, "tri").
multiplicative_prefix(4, "tetra").
multiplicative_prefix(5, "penta").
multiplicative_prefix(6, "hexa").
multiplicative_prefix(7, "hepta").
multiplicative_prefix(8, "octa").
multiplicative_prefix(9, "nona").
multiplicative_prefix(10, "deca").
multiplicative_prefix(11, "undeca").
multiplicative_prefix(12, "dodeca").
multiplicative_prefix(13, "trideca").
multiplicative_prefix(14, "tetradeca").
multiplicative_prefix(15, "pentadeca").
multiplicative_prefix(16, "hexadeca").
multiplicative_prefix(17, "heptadeca").
multiplicative_prefix(18, "octadeca").
multiplicative_prefix(19, "nonadeca").
multiplicative_prefix(20, "icosa").
multiplicative_prefix(21, "henicosa").
multiplicative_prefix(22, "docosa").
multiplicative_prefix(23, "tricosa").
multiplicative_prefix(30, "triaconta").
multiplicative_prefix(31, "hentriaconta").
multiplicative_prefix(35, "pentatriaconta").
multiplicative_prefix(40, "tetraconta").
multiplicative_prefix(48, "octatetraconta").
multiplicative_prefix(50, "pentaconta").
multiplicative_prefix(52, "dopentaconta").
multiplicative_prefix(60, "hexaconta").
multiplicative_prefix(70, "heptaconta").
multiplicative_prefix(80, "octaconta").
multiplicative_prefix(90, "nonaconta").
multiplicative_prefix(100, "hecta").
multiplicative_prefix(200, "dicta").
multiplicative_prefix(500, "pentacta").
multiplicative_prefix(1000, "kilia").
multiplicative_prefix(2000, "dilia").
multiplicative_ligand_prefix(2, "bis").
multiplicative_ligand_prefix(3, "tris").
multiplicative_ligand_prefix(4, "tetrakis").
multiplicative_ligand_prefix(5, "pentakis").
multiplicative_ligand_prefix(6, "hexakis").
multiplicative_ligand_prefix(7, "heptakis").
multiplicative_ligand_prefix(8, "octakis").
multiplicative_ligand_prefix(9, "nonakis").
multiplicative_ligand_prefix(10, "decakis").


% Element
element_name("H", hydrogen).
element_name("He", helium).
element_name("Li", lithium).
element_name("Be", beryllium).
element_name("B", boron).
element_name("C", carbon).
element_name("N", nitrogen).
element_name("O", oxygen).
element_name("F", fluorine).
element_name("Ne", neon).
element_name("Na", sodium).
element_name("Mg", magnesium).
element_name("Al", aluminum).
element_name("Si", silicon).
element_name("P", phosphorus).
element_name("S", sulfur).
element_name("Cl", chlorine).
element_name("Ar", argon).
element_name("K", potassium).
element_name("Ca", calcium).
element_name("Sc", scandium).
element_name("Ti", titanium).
element_name("V", vanadium).
element_name("Cr", chromium).
element_name("Mn", manganese).
element_name("Fe", iron).
element_name("Co", cobalt).
element_name("Ni", nickel).
element_name("Cu", copper).
element_name("Zn", zinc).
element_name("Ga", gallium).
element_name("Ge", germanium).
element_name("As", arsenic).
element_name("Se", selenium).
element_name("Br", bromine).
element_name("Kr", krypton).
element_name("Rb", rubidium).
element_name("Sr", strontium).
element_name("Y", yttrium).
element_name("Zr", zirconium).
element_name("Nb", niobium).
element_name("Mo", molybdenom).
element_name("Tc", technitium).
element_name("Ru", ruthenium).
element_name("Rh", rhodium).
element_name("Pd", palladium).
element_name("Ag", silver).
element_name("Cd", cadmium).
element_name("In", indium).
element_name("Sn", tin).
element_name("Sb", antimony).
element_name("Te", tellurium).
element_name("I", iodine).
element_name("Xe", xenon).
element_name("Cs", cesium).
element_name("Ba", barium).
element_name("La", lanthanum).
element_name("Ce", cerium).
element_name("Pr", praseodymium).
element_name("Nd", neodymium).
element_name("Pm", promethium).
element_name("Sm", samarium).
element_name("Eu", europium).
element_name("Gd", gadolinium).
element_name("Tb", terbium).
element_name("Dy", dysprosium).
element_name("Ho", holmium).
element_name("Er", erbium).
element_name("Tm", thulium).
element_name("Yb", ytterbium).
element_name("Lu", lutetium).
element_name("Hf", hafnium).
element_name("Ta", tantalum).
element_name("W", tungsten).
element_name("Re", rhenium).
element_name("Os", osmium).
element_name("Ir", iridium).
element_name("Pt", platinum).
element_name("Au", gold).
element_name("Hg", mercury).
element_name("Tl", thallium).
element_name("Pb", lead).
element_name("Bi", bismuth).
element_name("Po", polonium).
element_name("At", astatine).
element_name("Rn", radon).
element_name("Fr", francium).
element_name("Ra", radium).
element_name("Ac", actinium).
element_name("Th", thorium).
element_name("Pa", protactinium).
element_name("U", uranium).
element_name("Np", neptumium).
element_name("Pu", plutonium).
element_name("Am", americium).
element_name("Cm", curium).
element_name("Bk", berkelium).
element_name("Cf", californium).
element_name("Es", einsteinium).
element_name("Fm", fermium).
element_name("Md", mendelevium).
element_name("No", nobelium).
element_name("Lr", lawrencium).
element_name("Rf", rutherfordium).
element_name("Db", dubnium).
element_name("Sg", seaorgium).
element_name("Bh", bhorium).
element_name("Hs", hassium).
element_name("Mt", meitnerium).
element_name("Ds", darmstadtium).
element_name("Rg", roentgenium).
element_name("Cn", copernicium).
element_name("Nh", nihonium).
element_name("Fl", flerovium).
element_name("Mc", moscovium).
element_name("Lv", livermorium).
element_name("Ts", tennessine).
element_name("Og", oganesson).


% EN
en("H", 2.2).
en("He", 0).
en("Li", 0.98).
en("Be", 1.57).
en("B", 2.04).
en("C", 2.55).
en("N", 3.04).
en("O", 3.44).
en("F", 3.98).
en("Ne", 0).
en("Na", 0.93).
en("Mg", 1.31).
en("Al", 1.61).
en("Si", 1.9).
en("P", 2.19).
en("S", 2.58).
en("Cl", 3.16).
en("Ar", 0).
en("K", 0.82).
en("Ca", 1).
en("Sc", 1.36).
en("Ti", 1.54).
en("V", 1.63).
en("Cr", 1.66).
en("Mn", 1.55).
en("Fe", 1.83).
en("Co", 1.88).
en("Ni", 1.91).
en("Cu", 1.9).
en("Zn", 1.65).
en("Ga", 1.81).
en("Ge", 2.01).
en("As", 2.18).
en("Se", 2.55).
en("Br", 2.96).
en("Kr", 3).
en("Rb", 0.82).
en("Sr", 0.95).
en("Y", 1.22).
en("Zr", 1.33).
en("Nb", 1.6).
en("Mo", 2.16).
en("Tc", 1.9).
en("Ru", 2.2).
en("Rh", 2.28).
en("Pd", 2.2).
en("Ag", 1.93).
en("Cd", 1.69).
en("In", 1.78).
en("Sn", 1.96).
en("Sb", 2.05).
en("Te", 2.1).
en("I", 2.66).
en("Xe", 2.6).
en("Cs", 0.79).
en("Ba", 0.89).
en("La", 1.1).
en("Ce", 1.12).
en("Pr", 1.13).
en("Nd", 1.14).
en("Pm", 0).
en("Sm", 1.17).
en("Eu", 0).
en("Gd", 1.2).
en("Tb", 0).
en("Dy", 1.22).
en("Ho", 1.23).
en("Er", 1.24).
en("Tm", 1.25).
en("Yb", 0).
en("Lu", 1.27).
en("Hf", 1.3).
en("Ta", 1.5).
en("W", 2.36).
en("Re", 1.9).
en("Os", 2.2).
en("Ir", 2.2).
en("Pt", 2.28).
en("Au", 2.54).
en("Hg", 2).
en("Tl", 1.62).
en("Pb", 2.33).
en("Bi", 2.02).
en("Po", 2).
en("At", 2.2).
en("Rn", 0).
en("Fr", 0.7).
en("Ra", 0.9).
en("Ac", 1.1).
en("Th", 1.3).
en("Pa", 1.5).
en("U", 1.38).
en("Np", 1.36).
en("Pu", 1.28).
en("Am", 1.3).
en("Cm", 1.3).
en("Bk", 1.3).
en("Cf", 1.3).
en("Es", 1.3).
en("Fm", 1.3).
en("Md", 1.3).
en("No", 1.3).
en("Lr", 1.3).
en("Rf", 0).
en("Db", 0).
en("Sg", 0).
en("Bh", 0).
en("Hs", 0).
en("Mt", 0).
en("Ds", 0).
en("Rg", 0).
en("Cn", 0).
en("Nh", 0).
en("Fl", 0).
en("Mc", 0).
en("Lv", 0).
en("Ts", 0).
en("Og", 0).


% number of protons
num_protons("H", 1).
num_protons("He", 2).
num_protons("Li", 3).
num_protons("Be", 4).
num_protons("B", 5).
num_protons("C", 6).
num_protons("N", 7).
num_protons("O", 8).
num_protons("F", 9).
num_protons("Ne", 10).
num_protons("Na", 11).
num_protons("Mg", 12).
num_protons("Al", 13).
num_protons("Si", 14).
num_protons("P", 15).
num_protons("S", 16).
num_protons("Cl", 17).
num_protons("Ar", 18).
num_protons("K", 19).
num_protons("Ca", 20).
num_protons("Sc", 21).
num_protons("Ti", 22).
num_protons("V", 23).
num_protons("Cr", 24).
num_protons("Mn", 25).
num_protons("Fe", 26).
num_protons("Co", 27).
num_protons("Ni", 28).
num_protons("Cu", 29).
num_protons("Zn", 30).
num_protons("Ga", 31).
num_protons("Ge", 32).
num_protons("As", 33).
num_protons("Se", 34).
num_protons("Br", 35).
num_protons("Kr", 36).
num_protons("Rb", 37).
num_protons("Sr", 38).
num_protons("Y", 39).
num_protons("Zr", 40).
num_protons("Nb", 41).
num_protons("Mo", 42).
num_protons("Tc", 43).
num_protons("Ru", 44).
num_protons("Rh", 45).
num_protons("Pd", 46).
num_protons("Ag", 47).
num_protons("Cd", 48).
num_protons("In", 49).
num_protons("Sn", 50).
num_protons("Sb", 51).
num_protons("Te", 52).
num_protons("I", 53).
num_protons("Xe", 54).
num_protons("Cs", 55).
num_protons("Ba", 56).
num_protons("La", 57).
num_protons("Ce", 58).
num_protons("Pr", 59).
num_protons("Nd", 60).
num_protons("Pm", 61).
num_protons("Sm", 62).
num_protons("Eu", 63).
num_protons("Gd", 64).
num_protons("Tb", 65).
num_protons("Dy", 66).
num_protons("Ho", 67).
num_protons("Er", 68).
num_protons("Tm", 69).
num_protons("Yb", 70).
num_protons("Lu", 71).
num_protons("Hf", 72).
num_protons("Ta", 73).
num_protons("W", 74).
num_protons("Re", 75).
num_protons("Os", 76).
num_protons("Ir", 77).
num_protons("Pt", 78).
num_protons("Au", 79).
num_protons("Hg", 80).
num_protons("Tl", 81).
num_protons("Pb", 82).
num_protons("Bi", 83).
num_protons("Po", 84).
num_protons("At", 85).
num_protons("Rn", 86).
num_protons("Fr", 87).
num_protons("Ra", 88).
num_protons("Ac", 89).
num_protons("Th", 90).
num_protons("Pa", 91).
num_protons("U", 92).
num_protons("Np", 93).
num_protons("Pu", 94).
num_protons("Am", 95).
num_protons("Cm", 96).
num_protons("Bk", 97).
num_protons("Cf", 98).
num_protons("Es", 99).
num_protons("Fm", 100).
num_protons("Md", 101).
num_protons("No", 102).
num_protons("Lr", 103).
num_protons("Rf", 104).
num_protons("Db", 105).
num_protons("Sg", 106).
num_protons("Bh", 107).
num_protons("Hs", 108).
num_protons("Mt", 109).
num_protons("Ds", 110).
num_protons("Rg", 111).
num_protons("Cn", 112).
num_protons("Nh", 113).
num_protons("Fl", 114).
num_protons("Mc", 115).
num_protons("Lv", 116).
num_protons("Ts", 117).
num_protons("Og", 118).


% alternate names 
synonymous("Sb", stibium).
synonymous("Cu", cuprum).
synonymous("Au", aurum).
synonymous("Fe", ferrum).
synonymous("Pb", plumbum).
synonymous("Hg", hydragyrum).
synonymous("K", kalium).
synonymous("Ag", argentum).
synonymous("Na", natrium).
synonymous("Sn", stannum).
synonymous("W", wolfram).
synonymous("Al", aluminium).


% parent hydride
parent_hydride_name("AlH3", "alumane").
parent_hydride_name("GaH3", "gallane").
parent_hydride_name("InH3", "indigane").
parent_hydride_name("TlH3", "thallane").
parent_hydride_name("CH4", "methane").
parent_hydride_name("SiH4", "silane").
parent_hydride_name("GeH4", "germane").
parent_hydride_name("SnH4", "stannane").
parent_hydride_name("PbH4", "plumbane").
parent_hydride_name("NH3", "azane").
parent_hydride_name("PH3", "phosphane").
parent_hydride_name("AsH3", "arsane").
parent_hydride_name("SbH3", "stibane").
parent_hydride_name("BiH3", "bismuthane").
