%

% multiplicative prefixes
multiplicative_prefix(1, "mono").
multiplicative_prefix(2, "di").
multiplicative_prefix(3, "tri").
multiplicative_prefix(4, "tetra").
multiplicative_prefix(5, "penta").
multiplicative_prefix(6, "hexa").
multiplicative_prefix(7, "hepta").
multiplicative_prefix(8, "octa").
multiplicative_prefix(9, "nona").
multiplicative_prefix(10, "deca").
multiplicative_prefix(11, "undeca").
multiplicative_prefix(12, "dodeca").
multiplicative_prefix(13, "trideca").
multiplicative_prefix(14, "tetradeca").
multiplicative_prefix(15, "pentadeca").
multiplicative_prefix(16, "hexadeca").
multiplicative_prefix(17, "heptadeca").
multiplicative_prefix(18, "octadeca").
multiplicative_prefix(19, "nonadeca").
multiplicative_prefix(20, "icosa").
multiplicative_prefix(21, "henicosa").
multiplicative_prefix(22, "docosa").
multiplicative_prefix(23, "tricosa").
multiplicative_prefix(30, "triaconta").
multiplicative_prefix(31, "hentriaconta").
multiplicative_prefix(35, "pentatriaconta").
multiplicative_prefix(40, "tetraconta").
multiplicative_prefix(48, "octatetraconta").
multiplicative_prefix(50, "pentaconta").
multiplicative_prefix(52, "dopentaconta").
multiplicative_prefix(60, "hexaconta").
multiplicative_prefix(70, "heptaconta").
multiplicative_prefix(80, "octaconta").
multiplicative_prefix(90, "nonaconta").
multiplicative_prefix(100, "hecta").
multiplicative_prefix(200, "dicta").
multiplicative_prefix(500, "pentacta").
multiplicative_prefix(1000, "kilia").
multiplicative_prefix(2000, "dilia").
multiplicative_ligand_prefix(2, "bis").
multiplicative_ligand_prefix(3, "tris").
multiplicative_ligand_prefix(4, "tetrakis").
multiplicative_ligand_prefix(5, "pentakis").
multiplicative_ligand_prefix(6, "hexakis").
multiplicative_ligand_prefix(7, "heptakis").
multiplicative_ligand_prefix(8, "octakis").
multiplicative_ligand_prefix(9, "nonakis").
multiplicative_ligand_prefix(10, "decakis").
